Debug: Temp Rem self.add_special_tokens - need to restore under NOT-bloom condition
Traceback (most recent call last):
  File "openprompt_basic_classification.py", line 80, in <module>
    train_dataloader = PromptDataLoader(dataset=dataset["train"], template=mytemplate, tokenizer=tokenizer,
  File "/anaconda/envs/env_flan_38/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 101, in __init__
    self.tokenize()
  File "/anaconda/envs/env_flan_38/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 137, in tokenize
    inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
  File "/anaconda/envs/env_flan_38/lib/python3.8/site-packages/openprompt/plms/lm.py", line 93, in tokenize_one_example
    encoder_inputs = self.add_special_tokens(encoder_inputs=encoder_inputs) # this will do nothing in GPT2 tokenizer
  File "/anaconda/envs/env_flan_38/lib/python3.8/site-packages/openprompt/plms/utils.py", line 177, in add_special_tokens
    special_tokens_mask = np.array(self.tokenizer.get_special_tokens_mask(encoder_inputs[key]))
  File "/anaconda/envs/env_flan_38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3470, in get_special_tokens_mask
    assert already_has_special_tokens and token_ids_1 is None, (
AssertionError: You cannot use ``already_has_special_tokens=False`` with this tokenizer. Please use a slow (full python) tokenizer to activate this argument. Or set `return_special_tokens_mask=True` when calling the encoding method to get the special tokens mask in any tokenizer.